# MEO-LEO 集群路由训练配置文件

# 数据配置
data:
  data_file: "data/data.json"
  meo_data_file: "data/meo_data.json"
  use_generated_data: false

# 训练配置
training:
  num_episodes: 10
  max_steps_per_episode: 100
  batch_size: 32
  save_interval: 10 # 每多少个episode保存一次模型

# 强化学习参数
rl_agent:
  learning_rate: 0.1
  gamma: 0.9
  epsilon: 0.1
  epsilon_decay: 0.995
  epsilon_min: 0.01

# 环境参数
environment:
  load_threshold: 5
  max_load_per_satellite: 10
  reward_success: 10.0
  reward_failure: -8.0 # 增加失败惩罚
  reward_hop: -0.1
  reward_load_balance: 1.0
  reward_connectivity_penalty: -5.0 # 新增：连通性差的惩罚

# 网络参数
network:
  num_satellites: 10
  num_meo_satellites: 3
  num_time_slots: 50
  default_leo_altitude: 500.0

# 仿真参数
simulation:
  random_seed: 42
  num_training_queries: 10
  num_test_queries: 10
  ground_stations: 5

# 输出配置
output:
  log_level: "INFO"
  save_model: true
  model_save_path: "models/"
  log_file: "logs/training.log"
  plot_results: true
  results_path: "results/"
